### ISSUE TITLE
train parameters

### ISSUE THREAD

**Issue by 32l** [shamangary/Keras-MORPH-age-estimation#1]
Hi, 
very interested in your work. i hope to reproduce your training results, so could please share your training details? eg. input_size...

Best regards.

**Comment by shamangary** [comment]
Hi. I set image size to 64*64 as indicated in the default value of TYY_MORPH_create_db.py.
This is only a simple demo project. Feel free to discuss.

**Comment by 32l** [comment]
thx for reply.so can you share your training accuracy rates ?

**Comment by shamangary** [comment]
For now the small models (mobilenet and densenet) incline to overift. 
For regression:
Training MAE = 6 ~ 8 and 
validation MAE = 10 ~ 11.
For dex:
Training MAE > 9 and 
validation MAE > 9 
I think the small model is quite hard to learn robust feature for validation and training.

**Comment by 32l** [comment]
ok. BTW, how do you determine the num_output of last conv layer and last inner_product layer as 20 , 32 respectively, are there any guidelines?

**Comment by shamangary** [comment]
Since there is literally no paper working on small model age-estimation, all of my settings are purely experimental :)

If you know any paper is working on this area, plz share with me. Thanks!

**Comment by 32l** [comment]
Hi, shamangary. I've reimplement your work on Caffe these days. i got the similar result in mobilenet. And i wonder whether densenet performance better or not,  considering that it combines shallow and deep features.

**Comment by shamangary** [comment]
WOW your implementation is very fast. For now, I cannot see any improvement in densenet or mobilenet. I have tried (1) altering the size of the detected faces, (2) adding stronger feature augmentation, and (3) removing the faces which are not detected by dlib.

However, no improvement is found......
I will keep working on it......

**Comment by 32l** [comment]
well, looking for your improvement.

**Comment by shamangary** [comment]
Hi. It turns out I used inconsistent label and image in my preprocessing step.
I fix the error and add face align in the file. It should be working now :)

**Comment by 32l** [comment]
fantastic , i'll try it later.  Does this operation can obtain a significant increase in performance ?

**Comment by shamangary** [comment]
I get MAE= 4~5 for densenet_reg depth=13 for a more complex training version. I believe similar performance can be obtained.

**Comment by 32l** [comment]
oooh, that's amazing. this performance is almost catching up to the general model.

**Comment by shamangary** [comment]
More complete results are shown in our [IJCAI18] SSR-Net and our new github https://github.com/shamangary/SSR-Net

Feel free to check this out.
