### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by Zumbalamambo** [shamangary/Keras-MORPH-age-estimation#2]
can you please share the pretrained model for testing?

**Comment by shamangary** [comment]
OK. I will put them up later.

**Comment by shamangary** [comment]
Sorry for the late reply. I was working on the submission of the paper. The pre-trained models of each case are provided in our new paper [IJCAI18] SSR-Net.

Plz check
https://github.com/shamangary/SSR-Net
